var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/auth/forgot-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__03gg5sg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0knlbee._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0pgxyn5.js")
R.c("server/chunks/ssr/[root-of-the-server]__05z9ppr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__090jxzh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09pmjhv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_auth_forgot-password_page_actions_08p0wws.js")
R.m(70794)
module.exports=R.m(70794).exports
