// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/auth/forgot-password" | "/auth/login" | "/auth/signup" | "/cities" | "/dashboard" | "/profile" | "/trip/[slug]" | "/trips" | "/trips/[id]" | "/trips/[id]/budget" | "/trips/[id]/builder" | "/trips/[id]/edit" | "/trips/[id]/notes" | "/trips/[id]/packing" | "/trips/new"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/auth/signup" | "/api/cities/[id]/activities" | "/api/cities/search" | "/api/notes/[id]" | "/api/packing/[id]" | "/api/stops/[id]" | "/api/stops/[id]/activities" | "/api/trips" | "/api/trips/[id]" | "/api/trips/[id]/expenses" | "/api/trips/[id]/notes" | "/api/trips/[id]/packing" | "/api/trips/[id]/share" | "/api/trips/[id]/stops" | "/api/users" | "/api/weather"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/signup": {}
  "/api/cities/[id]/activities": { "id": string; }
  "/api/cities/search": {}
  "/api/notes/[id]": { "id": string; }
  "/api/packing/[id]": { "id": string; }
  "/api/stops/[id]": { "id": string; }
  "/api/stops/[id]/activities": { "id": string; }
  "/api/trips": {}
  "/api/trips/[id]": { "id": string; }
  "/api/trips/[id]/expenses": { "id": string; }
  "/api/trips/[id]/notes": { "id": string; }
  "/api/trips/[id]/packing": { "id": string; }
  "/api/trips/[id]/share": { "id": string; }
  "/api/trips/[id]/stops": { "id": string; }
  "/api/users": {}
  "/api/weather": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/signup": {}
  "/cities": {}
  "/dashboard": {}
  "/profile": {}
  "/trip/[slug]": { "slug": string; }
  "/trips": {}
  "/trips/[id]": { "id": string; }
  "/trips/[id]/budget": { "id": string; }
  "/trips/[id]/builder": { "id": string; }
  "/trips/[id]/edit": { "id": string; }
  "/trips/[id]/notes": { "id": string; }
  "/trips/[id]/packing": { "id": string; }
  "/trips/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
