var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/trips/[id]/packing/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n~mwpk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~zf8bn.js")
R.c("server/chunks/ssr/_0e1t~1v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0knlbee._.js")
R.c("server/chunks/ssr/_0~rh_m4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__05z9ppr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__090jxzh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09pmjhv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_trips_[id]_packing_page_actions_0b~aw77.js")
R.m(15273)
module.exports=R.m(15273).exports
