// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trips/[id]/budget/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips/[id]/budget">> = Specific
  const handler = {} as typeof import("../../app/trips/[id]/budget/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trips/[id]/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips/[id]/builder">> = Specific
  const handler = {} as typeof import("../../app/trips/[id]/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trips/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/trips/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trips/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips/[id]">> = Specific
  const handler = {} as typeof import("../../app/trips/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trips/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips/new">> = Specific
  const handler = {} as typeof import("../../app/trips/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips">> = Specific
  const handler = {} as typeof import("../../app/trips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cities/[id]/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cities/[id]/activities">> = Specific
  const handler = {} as typeof import("../../app/api/cities/[id]/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cities/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cities/search">> = Specific
  const handler = {} as typeof import("../../app/api/cities/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/notes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/packing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packing/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/packing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stops/[id]/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stops/[id]/activities">> = Specific
  const handler = {} as typeof import("../../app/api/stops/[id]/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stops/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stops/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/stops/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trips/[id]/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/expenses">> = Specific
  const handler = {} as typeof import("../../app/api/trips/[id]/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trips/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/notes">> = Specific
  const handler = {} as typeof import("../../app/api/trips/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trips/[id]/packing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/packing">> = Specific
  const handler = {} as typeof import("../../app/api/trips/[id]/packing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trips/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/trips/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trips/[id]/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/share">> = Specific
  const handler = {} as typeof import("../../app/api/trips/[id]/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trips/[id]/stops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/stops">> = Specific
  const handler = {} as typeof import("../../app/api/trips/[id]/stops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips">> = Specific
  const handler = {} as typeof import("../../app/api/trips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather">> = Specific
  const handler = {} as typeof import("../../app/api/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
