var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/trips/[id]/edit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.ypmjh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_050c~9v.js")
R.c("server/chunks/ssr/node_modules_next_0hdoin1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0knlbee._.js")
R.c("server/chunks/ssr/[root-of-the-server]__05z9ppr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__090jxzh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09pmjhv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_trips_[id]_edit_page_actions_0usoi19.js")
R.m(54438)
module.exports=R.m(54438).exports
